# This is the main configuration file for the plugin
# You can add more roads by adding more road names
# and blocks to the list of blocks for each road

# display debug messages
debug: true

# maximum acceleration per tick
speedIncreaseRate: 0.1
# maximum deceleration per tick
speedDecayRate: 1

# action bar message to display when player is on a road
infoMessage: "You are on a road"

# Affected non-player living entities, may affect performance negatively
# See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
affectedEntities: [ ]
roads:
  road1:
    speed: 0.5
    blocks:
      - DIRT_PATH
  road2:
    speed: 3
    blocks:
      - ANY
      - GRAVEL
      - COBBLESTONE
      - COBBLESTONE
  road3:
    speed: 5
    blocks:
      - Any
      - STONE_BRICKS
      - GRAVEL
      - COBBLESTONE
      - COBBLESTONE
