name: EasyRoads
version: '${project.version}'
main: dev.kalbarczyk.easyroads.EasyRoads
api-version: '1.21.9'
authors: [ Tepeshini ]
description: Allows players to create predefined roads that will allow them to travel faster
commands:
  easyroads:
    description: Main command for EasyRoads
    usage: /easyroads <subcommand>
    permission: easyroads.admin
    aliases: [ er ]
    subcommands:
      list:
        description: List all roads "craftings"
        usage: /easyroads list
        permission: easyroads.list
      help:
        description: Show help
        usage: /easyroads help
        permission: easyroads.help
      reload:
        description: Reload plugin
        usage: /easyroads reload
        permission: easyroads.reload

permissions:
    easyroads:
        description: Main permission for EasyRoads
        default: op
    easyroads.list:
        description: Permission to list all roads Blocksets
        default: op
    easyroads.help:
        description: Permission to show help
        default: op
    easyroads.reload:
        description: Permission to reload plugin
        default: op